"""cascade delete codes_otp

Revision ID: 27f5284bedc6
Revises: 32d761dd778f
Create Date: 2026-07-20 16:22:23.237045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f5284bedc6'
down_revision: Union[str, Sequence[str], None] = '32d761dd778f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('codes_otp_utilisateur_id_fkey'), 'codes_otp', type_='foreignkey')
    op.create_foreign_key(None, 'codes_otp', 'utilisateurs', ['utilisateur_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'codes_otp', type_='foreignkey')
    op.create_foreign_key(op.f('codes_otp_utilisateur_id_fkey'), 'codes_otp', 'utilisateurs', ['utilisateur_id'], ['id'])
    # ### end Alembic commands ###
