"""ajout email utilisateurs et table codes_otp

Revision ID: 32d761dd778f
Revises: f00f858e14b2
Create Date: 2026-07-20 14:50:41.213571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d761dd778f'
down_revision: Union[str, Sequence[str], None] = 'f00f858e14b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codes_otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tentatives', sa.Integer(), nullable=False),
    sa.Column('utilise', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codes_otp_utilisateur_id'), 'codes_otp', ['utilisateur_id'], unique=False)
    op.add_column('utilisateurs', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_column('utilisateurs', 'email')
    op.drop_index(op.f('ix_codes_otp_utilisateur_id'), table_name='codes_otp')
    op.drop_table('codes_otp')
    # ### end Alembic commands ###
